# Generated by Django 3.1.6 on 2021-02-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='price_mp3',
        ),
    ]
