# Generated by Django 3.1.6 on 2021-02-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0006_auto_20210207_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='date_upload',
        ),
    ]
