# Generated by Django 3.1.6 on 2021-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0009_remove_beat_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
